[32m2025-05-18 21:02:57 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 186fe24a-4b2c-444b-a332-c0ac1e076105 - 51201 - LOGS_CAPTURED - Started capturing logs in process (pid: 51201).
[32m2025-05-18 21:02:57 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 186fe24a-4b2c-444b-a332-c0ac1e076105 - 51201 - get_dataframe_from_clickhouse - STEP_START - Started execution of step "get_dataframe_from_clickhouse".
[32m2025-05-18 21:02:57 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 186fe24a-4b2c-444b-a332-c0ac1e076105 - get_dataframe_from_clickhouse - Loading file from: /home/wnsgu/slife-dag-engine/.tmp_dagster_home_467trjgk/storage/table_name using PickledObjectFilesystemIOManager...
[32m2025-05-18 21:02:57 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 186fe24a-4b2c-444b-a332-c0ac1e076105 - 51201 - get_dataframe_from_clickhouse - LOADED_INPUT - Loaded input "table_name" using input manager "io_manager", from output "result" of step "table_name"
[32m2025-05-18 21:02:57 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 186fe24a-4b2c-444b-a332-c0ac1e076105 - 51201 - get_dataframe_from_clickhouse - STEP_INPUT - Got input "table_name" of type "String". (Type check passed).
[32m2025-05-18 21:02:57 +0900[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 186fe24a-4b2c-444b-a332-c0ac1e076105 - 51201 - get_dataframe_from_clickhouse - STEP_OUTPUT - Yielded output "result" of type "DataFrame". Warning! Type check failed.
[32m2025-05-18 21:02:57 +0900[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 186fe24a-4b2c-444b-a332-c0ac1e076105 - 51201 - get_dataframe_from_clickhouse - STEP_FAILURE - Execution of step "get_dataframe_from_clickhouse" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "DataFrame". Description: Value of type <class 'NoneType'> failed type check for Dagster type DataFrame, expected value to be of Python type pandas.core.frame.DataFrame.

Stack Trace:
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 513, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 557, in _type_check_and_store_output
    yield from _type_check_output(step_context, step_output_handle, output)
  File "/home/wnsgu/.pyenv/versions/3.11.0/envs/clickhouse_env/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 430, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
